apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
  {{- if .Values.linkerd.injectNamespace }}
  annotations:
    linkerd.io/inject: enabled
  {{- end }}
