apiVersion: v1
kind: Secret
metadata:
  name: tetris-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tetris.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.adminToken | quote }}
