apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gateway-api-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - cluster: gameplay-east
            server: "https://gameplay-east:6443"
          - cluster: gameplay-west
            server: "https://gameplay-west:6443"
          - cluster: gameplay-central
            server: "https://gameplay-central:6443"
          - cluster: scoring
            server: "https://scoring:6443"
          - cluster: platform
            server: "https://platform:6443"
  template:
    metadata:
      name: "gateway-api-crds-{{ .cluster }}"
      labels:
        component: gateway-api
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: tetris
      source:
        repoURL: https://github.com/kubernetes-sigs/gateway-api
        targetRevision: v1.2.1
        path: config/crd/standard
      destination:
        server: "{{ .server }}"
        namespace: default
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
          - ServerSideApply=true
          - Replace=true
