apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - cluster: gameplay-east
            server: "https://gameplay-east:6443"
          - cluster: gameplay-west
            server: "https://gameplay-west:6443"
          - cluster: gameplay-central
            server: "https://gameplay-central:6443"
          - cluster: scoring
            server: "https://scoring:6443"
          - cluster: platform
            server: "https://platform:6443"
  template:
    metadata:
      name: "linkerd-control-plane-{{ .cluster }}"
      labels:
        component: linkerd-control-plane
      annotations:
        argocd.argoproj.io/sync-wave: "2"
    spec:
      project: tetris
      source:
        repoURL: https://helm.buoyant.cloud
        chart: linkerd-enterprise-control-plane
        targetRevision: "*"
        helm:
          valuesObject:
            identityTrustAnchorsPEM: REPLACE_TRUST_ANCHOR_PEM
            identity:
              issuer:
                tls:
                  crtPEM: REPLACE_ISSUER_CRT_PEM
                  keyPEM: REPLACE_ISSUER_KEY_PEM
      destination:
        server: "{{ .server }}"
        namespace: linkerd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
