apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - cluster: gameplay-east
            server: "https://gameplay-east:6443"
          - cluster: gameplay-west
            server: "https://gameplay-west:6443"
          - cluster: gameplay-central
            server: "https://gameplay-central:6443"
          - cluster: scoring
            server: "https://scoring:6443"
          - cluster: platform
            server: "https://platform:6443"
  template:
    metadata:
      name: "linkerd-crds-{{ .cluster }}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: tetris
      source:
        repoURL: https://helm.buoyant.cloud
        chart: linkerd-enterprise-crds
        targetRevision: "*"
      destination:
        server: "{{ .server }}"
        namespace: linkerd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Replace=true
