apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - cluster: tetris-ap-east
            server: "https://tetris-ap-east:6443"
          - cluster: tetris-ap-central
            server: "https://tetris-ap-central:6443"
          - cluster: tetris-ap-south
            server: "https://tetris-ap-south:6443"
  template:
    metadata:
      name: "linkerd-crds-{{ .cluster }}"
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: tetris
      source:
        repoURL: https://helm.buoyant.cloud
        chart: linkerd-enterprise-crds
        targetRevision: "*"
      destination:
        server: "{{ .server }}"
        namespace: linkerd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - Replace=true
